CREATE DATABASE IF NOT EXISTS silk_shop;
USE silk_shop;
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS  gallery  (
 product_id  INT(10) NOT NULL AUTO_INCREMENT,
 product_title  VARCHAR(100) NOT NULL,
 product_category VARCHAR(100) NOT NULL,
 product_type VARCHAR(100) NOT NULL,
 product_image VARCHAR(50) default 'default_product_image.png',
 PRIMARY KEY(product_id)) ;

--
-- Dumping data for table gallery
--

INSERT INTO  gallery  (product_title , product_category, product_type, product_image ) VALUES
('Freedom', 'Picture', 'Wall picture', 'bird1.jpg'),
('Self love', 'Mandala', 'Window picture', 'mandala01.jpg'),
('Soul of garden', 'Picture', 'Wall picture', 'soulofgarden.jpg'),
('Affectionate pain', 'Mandala', 'Window picture', 'mandala02.jpg'),
('Self-confidence mandala', 'Mandala', 'Sewn silk product', 'pillow02.jpg'),
('Tit and flowers', 'Picture', 'Window picture', 'tit01.jpg'),
('Happy girl', 'Mandala', 'Sewn silk product', 'happygirl.jpg'),
('Skirt with bird', 'Picture', 'Sewn silk product', 'skirt.jpg'),
('Peace mandala', 'Mandala', 'Wall picture', 'peace.jpg'),
('Tit', 'Picture', 'Window picture', 'tit02.jpg'),
('Birds in the night', 'Picture', 'Wall picture', 'birdatnight.jpg'),
('Bird & Butterfly laptop bag', 'Picture', 'Sewn silk product', 'laptopbag.jpg'),
('Sunny mandala', 'Mandala', 'Wall picture', 'mandala07.jpg'),
('Svadhisthana feeling', 'Mandala', 'Window picture', 'mandala04.jpg'),
('Bug', 'Picture', 'Wall picture', 'bug.jpg'),
('Butterflies', 'Picture', 'Wall picture', 'butterfly.jpg'),
('Kolibri', 'Picture', 'Window picture', 'kolibri.jpg'),
('Breezy fish', 'Picture', 'Wall picture', 'fish.jpg'),
('Bird in embroidery', 'Picture', 'Sewn silk product', 'embroidery_pillow.jpg'),
('Pouch with dragonfly', 'Picture', 'Sewn silk product', 'dragonfly_bag.jpg'),
('Pouch with fox', 'Picture', 'Sewn silk product', 'fox_bag.jpg'),
('Consolation', 'Picture', 'Wall picture', 'consolation.jpg'),
('Jellyfish in the subconscious', 'Picture', 'Wall picture', 'jellyfish.jpg'),
('Eyes', 'Picture', 'Wall picture', 'eyes.jpg'),
('Pisces', 'Picture', 'Wall picture', 'fish02.jpg'),
('Spreading love', 'Mandala', 'Window picture', 'mandala13.jpg'),
('Autumn', 'Mandala', 'Window picture', 'mandala12.jpg'),
('Greedy cat', 'Picture', 'Wall picture', 'greedycat.jpg'),
('Balerina', 'Picture', 'Wall picture', 'balerina.jpg'),
('Stability', 'Mandala', 'Window picture', 'mandala03.jpg'),
('Spiritual bouquet', 'Mandala', 'Window picture', 'mandala05.jpg'),
('Hippy mandala', 'Mandala', 'Window picture', 'mandala06.jpg'),
('Hide and seek', 'Picture', 'Wall picture', 'hideandseek.jpg'),
('Stable love', 'Mandala', 'Window picture', 'mandala08.jpg'),
('Chirp chirp mandala', 'Mandala', 'Window picture', 'mandala09.jpg'),
('Parrots', 'Picture', 'Wall picture', 'parrot.jpg'),
('Owl Light', 'Picture', 'Wall picture', 'owl_lamp.jpg'),
('Sea life', 'Picture', 'Wall picture', 'sealife.jpg'),
('Turtle & jellyfishes', 'Picture', 'Wall picture', 'turtle_jellyfishes.jpg'),
('Flower mandala', 'Mandala', 'Window picture', 'mandala11.jpg'),
('Rainbow sea', 'Picture', 'Wall picture', 'rainbowsea.jpg'),
('Turtles bag', 'Picture', 'Sewn silk product', 'turtle_bag.jpg'),
('Poppy', 'Picture', 'Wall picture', 'poppy.jpg'),
('Purple butterfly', 'Picture', 'Wall picture', 'butterfly02.jpg'),
('Butterfly and yellow cubes', 'Picture', 'Sewn silk product', 'pillow03.jpg'),
('Self-esteem', 'Mandala', 'Window picture', 'mandala10.jpg'),
('Dog and cat', 'Picture', 'Wall picture', 'dogcat.jpg'),
('Flower', 'Picture', 'Wall picture', 'flower.jpg'),
('Sugar flies', 'Picture', 'Wall picture', 'sugarfly.jpg'),
('Tree in the sky', 'Picture', 'Wall picture', 'tree01.jpg'),
('Chakras', 'Picture', 'Wall picture', 'chakras.jpg'),
('Matyik', 'Picture', 'Wall picture', 'matyik.jpg'),
('Universal love', 'Picture', 'Wall picture', 'universallove.jpg'),
('Heads', 'Picture', 'Wall picture', 'heads.jpg'),
('After Mucha', 'Picture', 'Wall picture', 'muha01.jpg');